- fuji_server/helper/preprocessor.py
Fixed bug getRE3repositories(cls) set debug to True
> Fixed bug getRE3repositories(cls) set debug to True

- fuji_server/controllers/fair_check.py
fixed missing namespaces from metadata_collector classes
> fixed provenance check

- fuji_server/helper/metadata_collector.py
- fuji_server/helper/metadata_collector_schemaorg.py
- fuji_server/helper/metadata_mapper.py
> some schema.org related fixes

- fuji_server/controllers/fair_check.py
- fuji_server/controllers/fair_object_controller.py
- fuji_server/evaluators/fair_evaluator_data_content_metadata.py
- fuji_server/evaluators/fair_evaluator_minimal_metadata.py
- fuji_server/evaluators/fair_evaluator_persistent_identifier.py
- fuji_server/evaluators/fair_evaluator_standardised_protocol_metadata.py
- fuji_server/helper/metadata_collector.py
- fuji_server/helper/metadata_collector_rdf.py
- fuji_server/helper/metadata_collector_xml.py
- fuji_server/helper/request_helper.py
- fuji_server/models/body.py
- fuji_server/yaml/swagger.yaml
datacite optional; request fixes; more and better logging messages
> Robbranch2

- requirements.txt
Hi, I think this dependency is needed.
Best, Wilko
> Add tldextract dependency

- examples/mass_assessment/Create_FAIR_assessment_report.ipynb
- examples/mass_assessment/fuji_mass_eval_template.py
and a basic notebook for report generation
The current status of the report is very basic and not very shiny. But I have not found any code of how Robert generates his reports for repositories (therefore so far I am reluctant to polish this example, because it is not clear if it will go to the trash at some point). 
So this does not have to be merged like it is ;-) I am happy for comments. I have used this so far for several repository evaluation and adapted it of course.
related to  #219
> Add example python script and for mass evaluation 

- pyproject.toml
Fixes the following issue: https://github.com/pangaea-data-publisher/fuji/issues/251
> Fix pyld missing (issue #251)

- pyproject.toml
This fixes https://github.com/pangaea-data-publisher/fuji/issues/257
> Fix markupsafe 2.1.0 conflict (#257)

- fuji_server/yaml/metrics_v0.5.yaml
> metricsv0.5 yaml edits

- fuji_server/helper/linked_vocab_helper.py
- fuji_server/helper/metadata_mapper.py
- Fixes #314.
- Also fixes a typo in terminal output.
> Add missing comma in metadata_mapper.py

- fuji_server/evaluators/fair_evaluator_semantic_vocabulary.py
- fuji_server/harvester/metadata_harvester.py
- fuji_server/yaml/metrics_v0.5.yaml
- Add 'metric_short_name' property to metric 1
- Remove duplicate log entry
- Remove leading space
> metric_short_name, duplicate log entry, leading space

- fuji_server/helper/preprocessor.py
- tests/conftest.py
- tests/helper/test_preprocessor.py
see https://en.wikipedia.org/wiki/Singleton_pattern
> chore: fix typos

- pyproject.toml
Proposed changes:
- remove unnecessary /** and /* from directory paths
- remove .txt suffix from authors file
- remove not existing changelog file
> chore: fix include section for build

- .pre-commit-config.yaml
- pyproject.toml
> chore: update pre-commit hooks

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
> chore: add github issue templates

- CONTRIBUTING.md
> chore: add contributor guide

- .github/workflows/ci.yml
- fuji_server/helper/linked_vocab_helper.py
- pyproject.toml
Follow-up PR to #407 
Related issue: #380
> chore: update remaining python dependencies

- .github/workflows/ci.yml
- .gitignore
- pyproject.toml
This PR proposes adding test coverage comments to incoming pull requests using a GitHub action.
> chore: add coverage comments to pull requests

- .github/dependabot.yml
> chore: add pip and docker section to dependabot config

- .gitignore
> chore: add .ruff_cache to .gitignore

- tests/api/test_urls.py
> test: add api url tests

- .github/workflows/reports.yml
This PR adds a header to the code coverage PR comment.
Related issue: #429
> ci: add header to code coverage report

- .pre-commit-config.yaml
> build: update pre-commit hooks

- Dockerfile
This reverts commit 3fb1ae127e6467eeccbf4400a17e41a92f37a7ce, reversing changes made to f1137c966161d6c38b06ab684788ad4b15986cc1.
Related issue: #454
> Revert "Merge pull request #445"

- .pre-commit-config.yaml
- docs/source/conf.py
- fuji_server/helper/request_helper.py
- pyproject.toml
Switch from black formatter to ruff code formatter.
Refs:
- https://docs.astral.sh/ruff/formatter/
> chore: switch from black to ruff formatter

- fuji_server/data/metadata_standards_uris.json
- fuji_server/evaluators/fair_evaluator_formal_metadata.py
- fuji_server/evaluators/fair_evaluator_license.py
- fuji_server/harvester/data_harvester.py
- fuji_server/harvester/metadata_harvester.py
- fuji_server/helper/linked_vocab_helper.py
- fuji_server/helper/metadata_collector.py
- fuji_server/helper/metadata_collector_rdf.py
- fuji_server/helper/metric_helper.py
- fuji_server/helper/preprocessor.py
- fuji_server/helper/request_helper.py
- pyproject.toml
- tests/helper/test_preprocessor.py
The ruff project recommends using dedicated `[tool.ruff.lint]` sections over `[tool.ruff]`.
This PR also activates the `E` group, see https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
> build: modernize ruff config

- pyproject.toml
Fixes #517 
The source code was not found on coveralls.io due to incorrect coverage.py settings.
> chore: change coverage root directory

- README.md
Make the badges nice and tidy in a table.
> docs: set up markdown badges in table
