pangaea-data-publisher/fuji

fuji_server/yaml/swagger.yaml

The specification https://swagger.io/specification/#contact-object requires eMail to `MUST be in the format of an email address`. To preserve both authors, I split one off into a separate https://swagger.io/specification/#specification-extensions

Split two emails into two fields.

---

Dockerfile

**Context:**
This PR originates from the EOSC-Synergy project (Software Quality Assurance as a Service), which receives funding from the EU.
It enables starting the server in Docker from another working directory too.

Add fuji_server module to Pythonpath

---

fuji_server/__main__.py
fuji_server/config/server.ini
fuji_server/yaml/swagger.yaml

Hi again, I have played a bit with the F-UJI API and added some features to deploy and use it on our servers. You will probably receive a few pull requests to improve the deployment in the coming days :) 
I added a parameter to the config file that allow the user to disable authentication (anyone can start an evaluation without any login). 
Enabling authentication is still the default behavior if the user don't do anything to disable it
You can try it in live there (current temp URL for the API deployed on our servers): https://fuji-137-120-31-148.sslip.io/fuji/api/v1/ui/
We might be interested in implementing OAuth in the future (e.g. ORCID login), but no auth currently fits better our use of the API

Enable to disable authentication

---

docker-compose.yml
fuji_server/__main__.py
requirements.txt

* Added the environment variable `ENABLE_CORS=true` to enable CORS request (to enable JavaScript client app to query the API from any URL), the default behavior stay the same (not enabled if environment variable not defined).
* Added forward headers to the `ProxyFix` to fix an issue with nginx reverse proxy (e.g. https://github.com/nginx-proxy/nginx-proxy).
* Updated the docker image in the `docker-compose.yml` to use the newly published image in the GitHub container registry and add the `ENABLE_CORS` environment variable
Thanks a lot!

Add CORS support and fix nginx reverse proxy fix

---

fuji_server/helper/request_helper.py

because, if we do (as currently), that avoids parsing the json in the `content_negotiate()` method 
this is described and reported in #329

do not accept application/json as a linkset content-type

---

pyproject.toml

Hi,
your build is using poetry. The official poetry documentation recommends updating the build-backend to `poetry-core`.
Refs: https://python-poetry.org/docs/pyproject/#poetry-and-pep-517

build: update build-backend to poetry-core

---

.pre-commit-config.yaml

Proposed changes:
- update the used pre-commit hooks in the config file to recent versions
- fix the indentation of the yaml file
- switch pre-commit/mirrors-yapf (DEPRECATED) to google/yapf
Refs: https://github.com/pre-commit/mirrors-yapf
Question: If you run `pre-commit run --all-files --color=always`, a lot of files get modified. Do you not enforce the style from the pre-commit-config so far?

chore: update pre-commit-config

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/publish-docker.yml
.github/workflows/python-publish.yml

Hi @huberrob,
this PR proposes the following changes:
- add a dependabot configutation for monthly updates of GitHub actions
- a first update of the used GitHub actions to recent versions
What do you think?

ci: add dependabot configuration

---

.github/workflows/ci.yml

Proposed changes:
- replace the key for hashing the cache filename from setup.json (not present anymore) to pyproject.toml
- replace pip install .[dev] with pip install .[testing], no docs dependencies are needed for testing
- remove "Install Latex compiler" step, the actual installation was commented anyway

ci: update ci jobs

---

.github/workflows/ci.yml

Proposed changes:
- run CI only on master branch and pull requests
- dependabot creates branches, which would otherwise run CI twice
- newer commits on the same branch or PR cancel older CI runs

ci: update ci run conditions

---

.github/workflows/ci.yml
README.md
pyproject.toml

I did not realize that [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) was only available from Python >= 3.8.
Which makes my approach to fix the single version location in #344 not working for Python 3.7.
But since 3.7 reached [end of life](https://endoflife.date/python) this year and receives no more security patches, I suggest dropping the support.
What do you think? Most users would nowadays use a more recent Python version anyway.
Refs: #357

chore: drop python 3.7 support

---

.github/workflows/ci.yml
pyproject.toml

I added a default hatch environment that can be accessed with:
```
hatch shell
```
Also I added a few script entries (formerly these were shell scripts), that can be run with:
```
hatch run test
```
or
```
hatch run lint
```

chore: add hatch envs and scripts

---

pyproject.toml

The autosemver dependency is not used in any workflow. Is that correct? Can it be removed to clean up the dependencies?

chore: remove obsolete autosemver dependency

---

fuji_server/helper/preprocessor.py

There was a bug in the get_licenses() method of the preprocessor.
Can line 589 be removed?
Refs: #388

fix: remove faulty function parameter

---

fuji_server/controllers/harvest_controller.py
fuji_server/encoder.py
fuji_server/models/base_model_.py
fuji_server/util.py
pyproject.toml

The "six" dependency is not needed, because this project does only support Python >= 3.8. So no compatibility layers with Python 2 are needed.

chore: remove obsolete six dependency

---

fuji_server/helper/catalogue_helper_datacite.py
fuji_server/helper/catalogue_helper_mendeley_data.py

Using `import requests as re` is a bad idea. `re` is the name of the regular expressions package from the python standard library. So in case, you ever want to use regular expressions in those modules, you get a name clash. Please use requests instead.

chore: replace ambiguous import requests as re

---

CONTRIBUTING.md

This PR adds links from the contributor guide directly to the issue tracker's labels.

docs: add links to issue tracker in contributing

---

CONTRIBUTING.md

This PR removes an unnecessary line in the dev setup description.

docs: remove unnecessary line in contributor guide

---

.github/workflows/ci.yml

This PR proposes the following changes:
- replace pip with python -m pip, more explicit
- rename ci caches
- use ubuntu 22.04 for all ci jobs
- add python 3.11 to tests
- run tests with hatch

chore: update ci jobs

---

fuji_server/harvester/metadata_harvester.py
fuji_server/helper/identifier_helper.py
fuji_server/helper/metadata_collector_xml.py

During the tests Python throws several `DeprecationWarning`s, because of `invalid escape sequence`s.

fix: make re-strings raw strings to fix DeprecationWarnings

---

.pre-commit-config.yaml

This PR proposes adding a pre-commit hook, that automatically sorts the contents or *.txt files in data/.

chore: add file-contents-sorter pre-commit hook

---

fuji_server/__main__.py

The new version of flask-limiter changed its API and wanted requires only arguments, except key_func.

fix: flask limiter error

---

fuji_server/__main__.py
fuji_server/app.py
tests/conftest.py

The application factory is commonly named create_app. Also there is no need to keep the application factory in its own package, if there is only one module present.
Related issue: #390

refactor: move application factory

---

.github/workflows/publish-docker.yml

This PR disables the Docker build in forked repositories. Also the job failed every time in the push step.

ci: add rule to disable docker build in forks

---

.github/workflows/ci.yml
.github/workflows/reports.yml
.gitignore
pyproject.toml

This is a new attempt to publish test and coverage reports.
This workflow is proposed in https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches.
The Pytest run will generate a junit XML file containing the test results. This file will be uploaded as an artifact. After the CI workflow is finished, another workflow ("Reports") will start and download the test results, generate a job summary and it also be able to comment on PRs.
After that a similar approach is taken to publish code coverage as well.
Related issue: #429

ci: publish pytest results

---

fuji_server/__main__.py
fuji_server/app.py

This PR fixes a bug that was introduced in #421.
- rename application factory to follow flask conventions (create_fuji_app -> create_app)
- remove obsolete .parent resulting in wrong path in create_app
Related issue: #390

fix: rename application factory

---

.github/dependabot.yml

This PR proposes the following changes:
- add a Dependabot group for GitHub Actions. So instead of multiple PRs per Action, you get a single PR combining all Action updates. The feature was added in 2023.
Refs:
- https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

ci: add github-actions group to dependabot config

---

fuji_server/data/metadata_standards_uris.json

Minor fix of typo in EGL URL, as reported in #471.
Related issue: #471
Broken URL.
* Tested new versus old URL in webbrowser.
* ran tests locally (`hatch run test tests/api`), which succeeded, but it also did before this fix. Adding a new test for this trivial change seems exaggerated though.
n/a

FIX: fix OGP URLs, see #471

---

.github/dependabot.yml
Dockerfile
README.md
pyproject.toml

The project supports Python 3.11, but not 3.12.
Related issues: #454

build: set requires-python setting to 3.11 only

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
pyproject.toml

This PR adds a coverage badge to the README showing the percentage of code coverage in the project. Also it deploys a code coverage HTML report to GitHub pages.
Example: https://afuetterer.github.io/fuji/coverage/

ci: add coverage badge and report

---

.pre-commit-config.yaml
fuji_server/helper/metadata_collector_rdf.py
fuji_server/helper/request_helper.py
fuji_server/util.py
metrics_configuration.md
pyproject.toml
tests/helper/test_preprocessor.py

This PR updates the pre-commit hooks. It also fixes the currently broken lint job status by applying the pre-commit hooks on the code base.
Lastly I added a few rules to the ignore list and added a note. `ruff` usually does not fix logging messages to use f-strings, but with this code base, it does not understand that self.logger in an inherited class is actually a logger. I can't think of a way to fix this right now, so I added those rules to ignore list.

build: update pre-commit hooks

---

.github/workflows/ci.yml

This PR replaces the custom lint job with the official [pre-commit/action](https://github.com/pre-commit/action), which takes care of caching as well.

ci: replace custom lint job with pre-commit/action

---

CONTRIBUTING.md
pyproject.toml

This PR adds a few minor improvements to the code base.

chore: housekeeping

---

.github/workflows/ci.yml
CONTRIBUTING.md
pyproject.toml

This PR moves from the custom optional dependency group testing to using the hatch testing config. The tests now run in random order as a default to find tests that depend on a certain order of running.
Instead of
```console
$ hatch run test
```
You can now do
```console
$ hatch test
```
Instead of 
```console
$ hatch run cov
```
It is
```console
$ hatch test --cover # or
$ hatch test -c 
```
Tests can run in parallel with
```console
$ hatch test --parallel # or
$ hatch test -p
```
These can be combined to:
```console
$ hatch test --cover --parallel # or
$ hatch test -cp
```
What do you think?

build: switch to hatch test environment

---

fuji_server/app.py
pyproject.toml

According to the connexion docs and their migration guide to 3.0, it is no longer possible to use `Flask-Cors`. I added the snippet from their docs and removed Flask-Cors from the deps.
Refs:
- https://connexion.readthedocs.io/en/latest/v3.html#flask-extensions-and-wsgi-middleware
- https://connexion.readthedocs.io/en/latest/cookbook.html#cors

build: switch to connexion middleware for cors
